### ISSUE TITLE
Maze height capped at 50

### ISSUE THREAD

**Issue by Tommmmy02** [GorgeousOne/Tangled-Maze-2#10]
Dont unterstand if i should open the issue but here it is 😆 

**Describe the bug**  
Maze height cant get over 50

**Errors Messages / Screenshots**  
No Errors

**To Reproduce**  
Steps to reproduce the behavior for example:
build a maze with height over 50

**Minecraft version**  
1.19.2

**Additional context**  
/

**Comment by GorgeousOne** [comment]
It’s more like a feature suggestion :D what would you suggest how higher should be possible?

**Comment by Tommmmy02** [comment]
Haha yeah your right. 

Was it always capped at 50? Then i dont saw it.
But mabye from bedrock to build Limit if possible. Surely crashes Server everytime. Then mabye just to 80-100 :D

**Comment by GorgeousOne** [comment]
new height capped at 128
