### ISSUE TITLE
Support plotsquared

### ISSUE THREAD

**Issue by TomLewis** [GorgeousOne/Tangled-Maze-2#12]
**Is your feature request related to a problem? Please describe.**  
In creative plots, you can create a maze that will automatically place over someone elses plot in plotsquared.

**Describe the solution you'd like**  
Dont generate parts of the maze in plots that are not yours

**Describe alternatives you've considered**  
Admin only use of the plugin

**Additional context**  
https://www.spigotmc.org/resources/plotsquared-v7.77506/

**Comment by TomLewis** [comment]
oof

**Comment by GorgeousOne** [comment]
Nope, I think there is way to many ways you can use this plugin to lag your server. I think it's simply to much effort for me to make this child save. It's staying a staff only plugin, you have to use it with caution
