### ISSUE TITLE
1.19 not working

### ISSUE THREAD

**Issue by Tommmmy02** [GorgeousOne/Tangled-Maze-2#8]
Love this plugin for a project with my friends.

Sadly 1.19 is not working at the moment.

**Comment by Euphonique** [comment]
+1

**Comment by GorgeousOne** [comment]
Hello,
I've ran the plugin on 1.19.2 and I did not encounter any errors straight away.

May I ask you to provide any error messages that occur, or steps to reproduce unexpected behaviour?
Thanks!

**Comment by Tommmmy02** [comment]
Hey there sure, here you go :)

Describe the bug
**Labyrinth build is not working**

Errors Messages / Screenshots
![console](https://user-images.githubusercontent.com/84730912/187228670-77c2133f-106a-4ff0-8e11-caa79b26e1d4.JPG)
![image](https://user-images.githubusercontent.com/84730912/187228736-c236f361-a42b-42dc-b87f-ec7e5b8020cc.png)

To Reproduce
Steps to reproduce the behavior for example:

**Select a rectangle maze
Run command "/tangledmaze build block_xy
Get error message**

Minecraft version
**Tested it on 1.19 and 1.19.2**

**Comment by Euphonique** [comment]
I get no errors. Nothing in the log.
I generated a flat standard world and it generates the mazes, but too high up flying in the sky.

**Comment by Tommmmy02** [comment]
> I get no errors. Nothing in the log. I generated a flat standard world and it generates the mazes, but too high up flying in the sky.

Oh mhh that is interesting.🤔 Mabye dev knows more

**Comment by GorgeousOne** [comment]
@Euphonique I tried to fix the building below Y:0 issue with the 2.1.0 update

@Tommmmy02 Mhh could be that this bug is related to Y-coordinates too. Does the error occur everywhere? I only managed to reproduce it by building (parts of) a maze at exactly Y:-1 😂
If that is the case for you I think the new update should fix that too.

**Comment by Tommmmy02** [comment]
Perfect, last update fixed it. 

Sadly the wall height cant get over 50 now, if i doing nothing wrong.

**Comment by GorgeousOne** [comment]
Oops I capped it at 50. but I’m not sure why I did this ^^ time for a new issue
